// Shared service section catalog with rich detail for the interactive modal
import { Cog, Wrench, ShieldCheck, Activity, Truck, Bot, Zap, Snowflake, Settings, Wind } from "lucide-react";

export const SERVICE_SECTIONS = [
  {
    key: "motor-turbo",
    moduleKey: "engine",
    icon: Cog,
    code: "01",
    title: "Motor & Turbo",
    short: "Komple motor revizyonu, turbo onarımı, EGR ve enjektör servisi.",
    long: "Ağır vasıta motorlarının A'dan Z'ye onarımı. Krank-kam mili işlemleri, segman, supap taşlama, turbo balans, intercooler kontrolü ve common-rail enjektör temizliği yapılır. Bosch yetkili teknisyen kadromuz tüm marka motorlara müdahale eder.",
    scope: [
      "Komple motor revizyonu (krank, kam mili, blok)",
      "Turbo balans, kartuş ve waste-gate onarımı",
      "EGR vana temizlik ve programlama",
      "Enjektör test, ultrasonik temizlik ve kalibrasyon",
      "Yağ kaçağı, soğutma ve egzoz manifoldu tamiri",
    ],
    commonIssues: [
      "Rölantide titreme / düzensiz çalışma",
      "Yağ basıncı düşüş uyarısı",
      "Yük altında çekiş kaybı",
      "Turbodan ıslık benzeri ses",
      "Boost basıncı kaçağı",
    ],
    duration: "1 — 5 iş günü",
    warranty: "12 ay / 100.000 km",
  },
  {
    key: "transmission",
    moduleKey: "transmission",
    icon: Wrench,
    code: "02",
    title: "Şanzıman & Diferansiyel",
    short: "Manuel ve otomatik şanzıman revizyonu, debriyaj, kavrama.",
    long: "Manuel, AMT ve otomatik tüm şanzıman tipleri için tam revizyon hizmeti. Senkromeç, dişli, debriyaj baskısı, volan ve diferansiyel onarımı. Şanzıman yağı analiz ile aşınma takibi.",
    scope: [
      "Manuel & AMT şanzıman revizyonu",
      "Otomatik şanzıman valf bloğu ve hidrolik kontrol",
      "Debriyaj seti (baskı + balata + bilya) değişimi",
      "Diferansiyel pinyon-ayna ayarı",
      "Şanzıman yağı analizi ve değişimi",
    ],
    commonIssues: [
      "Vites geçişinde sertlik veya kaçırma",
      "Debriyajda kayma / yanık koku",
      "Diferansiyelden uğultu",
      "3. vites senkromeç aşınması",
    ],
    duration: "2 — 7 iş günü",
    warranty: "12 ay / 80.000 km",
  },
  {
    key: "brake",
    moduleKey: "brake",
    icon: ShieldCheck,
    code: "03",
    title: "Fren Sistemleri",
    short: "ABS/EBS test, disk-balata, hava sistemleri, hortum.",
    long: "Hava-fren ve hidrolik fren tüm sistemler için kapsamlı servis. ABS/EBS arıza kodları okuma, sensör değişimi, kompresör ve regülatör revizyonu, balata-disk değişimi.",
    scope: [
      "ABS / EBS / RSS diagnostik ve programlama",
      "Fren balatası, disk ve kampana değişimi",
      "Hava kompresörü ve kurutucu revizyonu",
      "Fren hortumu, klape ve valf yenileme",
      "El freni ve yardımcı fren ayarı",
    ],
    commonIssues: [
      "Fren mesafesi artması",
      "ABS sensör arızası (gösterge ışığı)",
      "Hava kaçağı / kompresör çalışma süresi artışı",
      "Pedal süngerimsi hissi",
    ],
    duration: "1 — 3 iş günü",
    warranty: "12 ay / 60.000 km",
  },
  {
    key: "electrical",
    moduleKey: "electrical",
    icon: Activity,
    code: "04",
    title: "Elektrik & Diagnostik",
    short: "OBD diagnostik, ECU programlama, aydınlatma ve şarj sistemleri.",
    long: "Tüm marka ECU'lar için OBD/EOBD/Jaltest diagnostik. ECU yeniden programlama (chip-tuning değil), kablo demeti onarımı, akü-alternatör-marş motoru servisi.",
    scope: [
      "Çok markalı diagnostik tarama (Jaltest, Texa)",
      "ECU okuma, yazma ve programlama",
      "Akü-alternatör test ve onarım",
      "Marş motoru yenileme",
      "Kablo demeti onarım ve izolasyon",
    ],
    commonIssues: [
      "Akü voltaj dalgalanması",
      "ECU hata kodları (P0301, P0420 vb.)",
      "Şüpheli kontak noktaları",
      "Kontak verince marş yok",
    ],
    duration: "Aynı gün — 2 iş günü",
    warranty: "6 ay / 50.000 km",
  },
  {
    key: "periodic",
    moduleKey: "periodic",
    icon: Truck,
    code: "05",
    title: "Periyodik Bakım",
    short: "Yağ, filtre, antifriz, hortum kontrolleri ve raporlama.",
    long: "Üretici takvimine uygun planlı bakım. KM/saat bazlı bakım hatırlatma, 80+ noktalı kontrol listesi, detaylı dijital rapor.",
    scope: [
      "Motor yağı + 4 filtre (yağ/hava/yakıt/kabin)",
      "Antifriz, fren yağı, hidrolik yağ değişimi",
      "Kayış-gergi rulmanları kontrolü",
      "80 noktalı durum kontrol listesi",
      "Dijital rapor + KM takvimi",
    ],
    commonIssues: [
      "Bakım uyarısı / km aşımı",
      "Motor yağı kalitesi düşüşü",
      "Hava filtresi tıkanması",
    ],
    duration: "Aynı gün",
    warranty: "Bakım garantisi: 6 ay",
  },
  {
    key: "ai",
    moduleKey: "ai_diagnostic",
    icon: Bot,
    code: "06",
    title: "AI Destekli Tanı",
    short: "Servis geçmişinize göre tekrarlayan arıza analizi ve öneriler.",
    long: "Claude Sonnet 4.5 modeli ile çalışan diagnostik asistan. Aracınızın tüm servis kayıtlarını analiz ederek tekrarlayan arızaları tespit eder, olası nedenleri açıklar ve önleyici bakım önerileri sunar.",
    scope: [
      "Modül-bazlı (motor/turbo/fren vb.) tekil analiz",
      "Tekrarlayan arıza tespiti (son 6 ay)",
      "Aciliyet seviyesi belirleme (düşük—kritik)",
      "Önerilen tanı adımları ve onarım aksiyonları",
      "Sohbet tabanlı arıza danışmanlığı (Türkçe)",
    ],
    commonIssues: [
      "Uyarı lambası yanıyor — nereden başlamalı?",
      "Aynı arıza 3. kez tekrarlıyor",
      "Hangi parça önce değişmeli?",
    ],
    duration: "Anında (saniyeler içinde)",
    warranty: "AI önerisi profesyonel teşhisin yerini tutmaz",
  },
];

// Full 9-item catalog for Hizmetler page (re-uses first 6 + 3 extras)
export const SERVICES_FULL = [
  ...SERVICE_SECTIONS.slice(0, 4),
  {
    key: "ac-cooling",
    moduleKey: "electrical",
    icon: Snowflake,
    code: "06",
    title: "Klima & Soğutma",
    short: "Klima kompresör değişimi, gaz dolumu, radyatör ve hortum revizyonu.",
    long: "R134a ve R1234yf gazlı sistemler için tam klima servisi. Radyatör, intercooler ve soğutma hortumları yenilemesi.",
    scope: [
      "Klima kompresörü değişimi",
      "Soğutucu gaz dolumu (R134a / R1234yf)",
      "Radyatör temizlik / değişim",
      "Kabin filtresi yenilenmesi",
      "Sızdırmazlık testi",
    ],
    commonIssues: [
      "Klima soğutmuyor",
      "Kompresörden ses geliyor",
      "Soğutma sıvısı eksiliyor",
    ],
    duration: "Aynı gün",
    warranty: "12 ay",
  },
  {
    key: "hydraulics",
    moduleKey: "engine",
    icon: Settings,
    code: "07",
    title: "Yağlama & Hidrolik",
    short: "Direksiyon, hidrolik silindir, yağ ve gres istasyonu.",
    long: "Damper, vinç ve direksiyon hidrolik sistemlerinin servisi. Silindir keçe değişimi, pompa onarımı.",
    scope: [
      "Hidrolik silindir keçe değişimi",
      "Hidrolik pompa onarımı",
      "Direksiyon hidrolik servisi",
      "Yüksek basınçlı gres istasyonu",
    ],
    commonIssues: [
      "Direksiyonda ağırlık",
      "Damper inip kalkmıyor",
      "Hidrolik yağ sızıntısı",
    ],
    duration: "1 — 2 iş günü",
    warranty: "12 ay",
  },
  {
    key: "chassis",
    moduleKey: "brake",
    icon: Truck,
    code: "08",
    title: "Şasi & Süspansiyon",
    short: "Makas, amortisör, kingpin, dingil ve şasi kaynak işleri.",
    long: "Ağır yük altında çalışan şasi ve süspansiyon parçalarının tam servisi.",
    scope: [
      "Makas yaprağı değişimi",
      "Amortisör değişimi",
      "Kingpin & rotil değişimi",
      "Dingil ayarı (toe / camber)",
      "Şasi kaynak ve onarımı",
    ],
    commonIssues: [
      "Lastik düzensiz aşınması",
      "Şasi gıcırtısı",
      "Direksiyon serbest hareketi",
    ],
    duration: "1 — 4 iş günü",
    warranty: "12 ay",
  },
  SERVICE_SECTIONS[4], // periodic
  SERVICE_SECTIONS[5], // ai
];
